description: >-
  This task predicts whether a patient will have an abnormal blood sodium level in the next 24 hours,
  given the first 24 hours of their admission to the _icu_. Only patients whose _icu_ stay is
  at least 48 hours will be included to keep the consistency of the target windows across different
  patients. 

predicates:
  # ICU ADMISSION
  icu_admission_0:
    code: ICU_ADMISSION//Medical Intensive Care Unit (MICU)
  icu_admission_1:
    code: ICU_ADMISSION//Medical/Surgical Intensive Care Unit (MICU/SICU)
  icu_admission_2:
    code: ICU_ADMISSION//Cardiac Vascular Intensive Care Unit (CVICU)
  icu_admission_3:
    code: ICU_ADMISSION//Surgical Intensive Care Unit (SICU)
  icu_admission_4:
    code: ICU_ADMISSION//Trauma SICU (TSICU)
  icu_admission_5:
    code: ICU_ADMISSION//Coronary Care Unit (CCU)
  icu_admission_6:
    code: ICU_ADMISSION//Neuro Intermediate
  icu_admission_7:
    code: ICU_ADMISSION//Neuro Surgical Intensive Care Unit (Neuro SICU)
  icu_admission_8:
    code: ICU_ADMISSION//Neuro Stepdown
  icu_admission:
    expr: or(icu_admission_0,icu_admission_1,icu_admission_2,icu_admission_3,icu_admission_4,icu_admission_5,icu_admission_6,icu_admission_7,icu_admission_8)

  # ICU DISCHARGE
  icu_discharge_0:
    code: ICU_DISCHARGE//Medical Intensive Care Unit (MICU)
  icu_discharge_1:
    code: ICU_DISCHARGE//Medical/Surgical Intensive Care Unit (MICU/SICU)
  icu_discharge_2:
    code: ICU_DISCHARGE//Cardiac Vascular Intensive Care Unit (CVICU)
  icu_discharge_3:
    code: ICU_DISCHARGE//Surgical Intensive Care Unit (SICU)
  icu_discharge_4:
    code: ICU_DISCHARGE//Coronary Care Unit (CCU)
  icu_discharge_5:
    code: ICU_DISCHARGE//Trauma SICU (TSICU)
  icu_discharge_6:
    code: ICU_DISCHARGE//Neuro Intermediate
  icu_discharge_7:
    code: ICU_DISCHARGE//Neuro Stepdown
  icu_discharge_8:
    code: ICU_DISCHARGE//Neuro Surgical Intensive Care Unit (Neuro SICU)
  icu_discharge:
    expr: or(icu_discharge_0,icu_discharge_1,icu_discharge_2,icu_discharge_3,icu_discharge_4,icu_discharge_5,icu_discharge_6,icu_discharge_7,icu_discharge_8)

  sodium:
    code: LAB//50983//mEq/L
  normal_sodium:
    code: LAB//50983//mEq/L
    value_min: 135
    value_max: 145
    value_min_inclusive: True
    value_max_inclusive: True
  abnormally_low_sodium:
    code: LAB//50983//mEq/L
    value_max: 135
    value_max_inclusive: False
  abnormally_high_sodium:
    code: LAB//50983//mEq/L
    value_min: 145
    value_min_inclusive: False
  abnormal_sodium:
    expr: or(abnormally_low_sodium, abnormally_high_sodium)

trigger: icu_admission

windows:
  input:
    start: trigger
    end: start + 24h
    start_inclusive: True
    end_inclusive: True
    has:
      # do not allow hospital discharge happens in the input window (the first 24h)
      icu_admission: (None, 1)
      icu_discharge: (None, 0)
    index_timestamp: end
  target:
    start: input.end
    end: start + 24h
    start_inclusive: False
    end_inclusive: True
    has:
      # do not allow hospital discharge happens in the target window (the next 24h)
      icu_discharge: (None, 0)
      sodium: (1, None)
    label: abnormal_sodium
